INSERT INTO projects (title, description, features, tech_stack, image_url, project_url, user_id)
VALUES ('Tweeter',
 'Single page Ajax-based twitter clone using jQuery, HTML and CSS.', 
 'Post new tweets to the feed without reloading the page or being directed to a new URL. Error messages when tweets don''t meet requirements (empyt strings, over 140 character lenght). Responsive design featuring a desktop format and tablet/mobile format. Interactive highlights when hovering over tweets or clickables. Displays time since a tweet was posted. Functional character counter which indicates when the allowable number of caracters has been exceeded', 
 'Express, Node', 'https://github.com/7-O-2-H/tweeter/blob/master/docs/Desktop%20Tweet%20Feed.png?raw=true', 'https://github.com/7-O-2-H/tweeter', 
 5),
('Scheduler', 'React based app for scheduling appointments/interviews.', 
'Book appointments with mentors for assistance in a process similar to the one used by Lighthouse Labs. Users can book appointments with an available mentor in each of 5 available slots from Monday to Friday. Appointments can also be cancelled or edited.', 'React, Sass, JS; Tested with Cypress and Storybook', 
'https://github.com/7-O-2-H/scheduler/blob/master/docs/Full%20View%20of%20Application.png?raw=true',
'https://github.com/7-O-2-H/scheduler', 
5),
('Sneaker Vault', 
'Niche resale app in the style of ebay or kijiji for shoes with JS and express.',
'Admins can list sales and include images via urls. Users can send messages to sellers or contact them by e-mail using nodemailer. Users can favourite items and sort by subcategories',
'Express, JS, Sass, Nodemailer',
'https://raw.githubusercontent.com/010JGL/mid_term/master/docs/pics/Screen1.png',
'https://github.com/7-O-2-H/sneaker_vault',
5),
('Lonely Books', 
'A mini e-commerce application',
'Browse listings, view, buy, filter by price, mark favourites to check later and even send messages to the seller listing the item.',
'Node JS, Express, jQuery, CSS, PostgreSQL, Git',
'https://cdn.pixabay.com/photo/2019/02/14/14/38/book-3996723_1280.jpg',
'https://github.com/shilpashaji1204/buy_sell_listing_website',
7),
('Tiny App',
'TinyApp is a full stack web application built with Node and Express that allows users to shorten long URLs (à la bit.ly).',
'Create auto-generated short urls for you favourite web pages. Urls are saved to the user profile where they can edit or delete their urls as desired.',
'Node, Express, EJS',
'https://raw.githubusercontent.com/RorySchof/tinyapp/main/docs/Screenshot%202023-03-27%20at%2010.05.20%20PM.png',
'https://github.com/RorySchof/tinyapp',
5),
('Jungle',
'A mini e-commerce application built with Rails 6.1 for purposes of teaching Rails by example. This was not built from me from scratch. I fixed bugs and added features as listed below as well as developed RSpec tests.',
'Add Sold Out badge for out of stock products. Admin access for adding/reviewing product categories. Add order to cart and review order at checkout. Login and signup with user authentication. Tested with RSpec.',
'Ruby, Rails, PostgreSQL',
'https://github.com/7-O-2-H/jungle/blob/master/docs/Main%20Page%20-%20Products%20Index.png?raw=true',
'https://github.com/7-O-2-H/jungle',
7);